affinityworks/main

.gitignore, README.md, config/database.yml
I just cloned the project for dev for the first time, and thought I'd apply that to making it slightly easier for people to get started
=> Improve cold setup

app/representers/api/event_representer.rb, db/migrate/20170228025254_rename_event_type.rb, db/schema.rb, test/fixtures/events.yml, test/models/api/event_test.rb
Fix conflict with Rails STI 'type' column convention
=> #13 Rename Event#type to Event#osdi_type

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/events_controller.rb, app/models/ability.rb, app/representers/json_api/events_representer.rb, config/routes.rb, test/controllers/events_controllers_test.rb, test/fixtures/people.yml
To support http://www.advocacycommons.org/mocks/event_manager.html
=> Add stub events controller with simple authentication and authorization

app/models/api/action_network/attendances.rb, app/models/api/action_network/import.rb, app/models/api/action_network/person.rb, app/representers/api/action_network/person_representer.rb, test/fixtures/files/person.json, test/models/api/action_network/attendances_test.rb, test/models/api/action_network/person_test.rb
[Issue #42](https://github.com/advocacycommons/advocacycommons/issues/42)
=> 42 import single member

app/models/api/action_network/attendances.rb, app/models/api/action_network/events.rb, app/models/api/action_network/import.rb, app/models/api/action_network/people.rb, app/models/api/action_network/person.rb, app/models/group.rb, db/migrate/20170424220747_add_synced_at_to_groups.rb, db/schema.rb, lib/tasks/action_network_syncer.rake
=> Add rake task for Action Network data import.

app/representers/api/resources/event_representer.rb, test/models/api/action_network/events_test.rb
=> Add location to event when importing.

app/controllers/events_controller.rb, client/app/bundles/Events/components/Events.jsx, client/app/bundles/Events/components/EventsFilter.jsx, test/controllers/events_controllers_test.rb, test/fixtures/people.yml
=> Add feature to filter events by title.

app/controllers/events_controller.rb, app/representers/json_api/event_representer.rb, app/representers/json_api/events_representer.rb, client/app/bundles/Events/components/Event.jsx
Show location and rsvps count in event attendances.
=> Show location

client/app/bundles/Events/components/Event.jsx, client/app/bundles/Events/components/EventAddress.jsx, client/app/bundles/Events/components/EventDetail.jsx, client/app/bundles/Events/components/Events.jsx, client/app/bundles/Events/components/EventsFilter.jsx, client/app/bundles/Events/routes/routes.jsx, client/package.json
=> Event show

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/views/application/_client.html.erb
=> Fix user dropdown style.

app/controllers/application_controller.rb, app/models/ability.rb, test/models/ability_test.rb, test/models/person_test.rb
=> Add CanCan rules.

app/controllers/application_controller.rb, app/controllers/events_controller.rb, test/controllers/events_controllers_test.rb
Also:
* Add workaround for current group on request with osdi api key.
* Fix broken test.
=> Fix request validation in EventsController.

app/models/person.rb
#83 
WIP: We still need to figure out what to do with the email column. See issue comments.
=> Login with multiple emails.

app/models/person.rb, db/migrate/20170504155342_remove_email_from_person.rb, db/schema.rb, test/controllers/api/v1/people_controller_test.rb, test/fixtures/people.yml, test/models/person_test.rb, test/representers/api/resources/person_representer_test.rb
=> Remove email

app/models/membership.rb, db/migrate/20170503191123_change_memberships_role_type_to_integer.rb, db/schema.rb, test/fixtures/memberships.yml, test/models/api/action_network/people_test.rb
=> Memberships role

client/app/bundles/Events/components/Attendance.jsx, client/app/bundles/Events/components/Attendances.jsx, client/app/bundles/Events/reducers/EventReducer.jsx
=> Update attendance faster

app/controllers/application_controller.rb, config/initializers/active_admin.rb, db/migrate/20170509230710_add_admin_to_user.rb, db/schema.rb, test/controllers/admin/sessions_controller_test.rb
=> Add active admin permission.

client/app/bundles/Events/components/Event.jsx
=> Use event name in admin page.

client/app/bundles/Events/components/EventDetail.jsx, client/app/bundles/Events/components/GoogleMap.jsx
=> Fix google map component.

.travis.yml
=> Configure TravisCI

app/models/api/action_network/import.rb
=> Retry AN requests.

app/models/api/action_network/import.rb
=> Fix modified date

app/controllers/application_controller.rb
=> Redirect organizer group members to members page after login.

client/app/bundles/Events/reducers/GroupsReducer.jsx
=> Fix groups page.

db/seeds.rb
=> Add seeds.

app/controllers/members_controller.rb, app/views/members/show.html.erb, client/app/bundles/Events/actions/MembersActions.jsx, client/app/bundles/Events/actions/types.jsx, client/app/bundles/Events/components/Member.jsx, client/app/bundles/Events/components/MemberDetail.jsx, client/app/bundles/Events/components/Members.jsx, client/app/bundles/Events/reducers/MemberReducer.jsx, client/app/bundles/Events/reducers/index.jsx, client/app/bundles/Events/routes/routes.jsx, config/routes.rb
=> Add member page.

app/models/api/action_network/events.rb, app/representers/api/action_network/event_representer.rb
=> Add creator in when importing events.

app/controllers/attendances_controller.rb, app/models/email_address.rb, app/models/membership.rb, db/migrate/20170524141505_add_unique_index_to_emails.rb, db/migrate/20170524141532_add_unique_index_to_memberships.rb, db/schema.rb, test/controllers/attendances_controller_test.rb, test/models/email_address_test.rb, test/models/membership_test.rb
=> Prevent memberships an emails duplication.

app/models/event.rb, test/models/api/action_network/events_test.rb, test/models/event_test.rb, test/models/group_test.rb
=> Don't show cancelled events.

test/controllers/members_controller_test.rb, test/models/group_test.rb
#196 
I refactor the test to not depend on unreliable information.
=> Fix intermintent tests.

app/models/api/action_network/import.rb, app/models/api/action_network/people.rb, app/models/api/action_network/person.rb, test/models/api/action_network/person_test.rb
=> Import tests

app/models/person.rb, test/models/person_test.rb
=> Make attendee phone number optional.

app/representers/api/collections/attendances_representer.rb, app/representers/api/collections/events_representer.rb, test/fixtures/files/events2.json, test/fixtures/files/events_page_2.json, test/models/api/action_network/events_test.rb, test/models/group_test.rb
=> Fix import event and attendance pagination.

app/controllers/application_controller.rb, app/controllers/imports_controller.rb, app/controllers/people/omniauth_callbacks_controller.rb, client/app/bundles/Events/actions/AttendancesActions.jsx, client/app/bundles/Events/actions/EventsActions.jsx, client/app/bundles/Events/actions/MembersActions.jsx, client/app/bundles/Events/components/AttendanceMatch.jsx, client/app/bundles/Events/components/Attendances.jsx, client/app/bundles/Events/components/Event.jsx, client/app/bundles/Events/components/EventDetail.jsx, client/app/bundles/Events/components/EventImport.jsx, client/app/bundles/Events/components/Member.jsx, client/app/bundles/Events/components/MemberDetail.jsx, client/app/bundles/Events/components/Nav.jsx, client/app/bundles/Events/components/RemoteEventMatch.jsx, client/app/bundles/Events/components/RemoteEventMatches.jsx, client/app/bundles/Events/containers/AttendanceMatching.jsx, client/app/bundles/Events/history.jsx, client/app/bundles/Events/routes/routes.jsx, client/app/bundles/Events/utils/Pathnames.jsx, config/routes.rb, test/controllers/attendances_controller_test.rb, test/controllers/events_controllers_test.rb, test/controllers/imports_controller_test.rb, test/controllers/members_controller_test.rb, test/integration/authentication_test.rb
=> 242 groups scope

client/app/bundles/Events/components/Nav.jsx, client/app/bundles/Events/containers/Dashboard.jsx, client/app/bundles/Events/containers/Groups.jsx
=> Add dashboard tab.

app/assets/stylesheets/application.scss, app/controllers/group_tags_controller.rb, app/representers/json_api/groups_representer.rb, app/representers/json_api/tags_representer.rb, client/app/bundles/Events/components/Group.jsx, client/app/bundles/Events/components/Tags.jsx, client/app/bundles/Events/utils/Pathnames.jsx, config/routes.rb, test/controllers/group_tags_controller_test.rb
=> 249 manage groups tags

client/app/bundles/Events/components/Header.jsx
=> Update Affinity logo size.

app/controllers/application_controller.rb, app/controllers/groups_controller.rb, app/controllers/memberships_controller.rb, client/app/bundles/Events/components/Groups.jsx, client/app/bundles/Events/routes/routes.jsx
=> Make groups column sortable.

client/app/bundles/Events/components/Group.jsx, client/app/bundles/Events/components/Groups.jsx, db/seeds.rb
=> Link to groups dashboard if national organizer.

client/app/bundles/Events/components/Header.jsx
=> Fix Header width.

client/app/bundles/Events/containers/Dashboard.jsx, db/migrate/20170606181147_change_groups_description_type_to_text.rb, db/schema.rb
Also:
* Change Groups description type to text.
related to #261.
=> Show Group description in Dashboard.

client/app/bundles/Events/components/Member.jsx, client/app/bundles/Events/components/Members.jsx
=> Allow to send email to several members.

app/representers/json_api/event_representer.rb, client/app/bundles/Events/components/EventDetail.jsx
=> Update event page.

app/admin/group.rb
@Matt-Holland needs this to change Group's description.
=> Add Group permitted parameters for Admin section.

app/controllers/application_controller.rb, app/controllers/events_controller.rb, app/controllers/groups_controller.rb, app/controllers/memberships_controller.rb, client/app/bundles/Events/components/Events.jsx
=> Make events columns sortable.

app/assets/stylesheets/application.scss, app/controllers/groups_controller.rb, client/app/bundles/Events/components/Breadcrumbs.jsx, client/app/bundles/Events/components/Groups.jsx, client/app/bundles/Events/components/Tags.jsx, client/app/bundles/Events/containers/Groups.jsx
Need to do the same for members and events in the future
=> Filter groups by tags.

app/controllers/event_tags_controller.rb, app/models/event.rb, app/representers/json_api/events_representer.rb, client/app/bundles/Events/components/Event.jsx, client/app/bundles/Events/components/Events.jsx, client/app/bundles/Events/components/Tags.jsx, client/app/bundles/Events/utils/Pathnames.jsx, config/routes.rb, test/controllers/event_tags_controller_test.rb
=> Add Tags to Events.

app/assets/stylesheets/application.scss, app/controllers/imports_controller.rb, app/models/facebook_event.rb, app/representers/json_api/attendances_representer.rb, app/representers/json_api/people_representer.rb, client/app/bundles/Events/components/Attendance.jsx, client/app/bundles/Events/components/AttendanceMatch.jsx, client/app/bundles/Events/components/Events.jsx, client/app/bundles/Events/components/FacebookLink.jsx, client/app/bundles/Events/components/RemoteEventMatch.jsx, client/app/bundles/Events/components/RemoteEventMatches.jsx, client/app/bundles/Events/containers/AttendanceMatching.jsx, db/seeds.rb, test/models/remote_event_test.rb
Also:
- Show attendances imported from fb.
=> Allow user to re sync facebook attendances.

app/models/person.rb, client/app/bundles/Events/containers/AttendanceImport.jsx, test/models/person_test.rb
Also:
* Fix when email is given and there is not user with that email.
=> Fix Event id when importing remote attendances.

client/app/bundles/Events/components/EventDetail.jsx
=> Fix error when Event have not creator.

app/views/layouts/application.html.erb
=> Fix flash rails side flash message style.

app/assets/stylesheets/application.scss, app/controllers/dashboard_controller.rb, app/models/attendance.rb, app/models/event.rb, app/models/person.rb, client/app/bundles/Events/actions/AlertsActions.jsx, client/app/bundles/Events/actions/GroupsActions.jsx, client/app/bundles/Events/actions/ProfileActions.jsx, client/app/bundles/Events/components/AttendanceActivityFeed.jsx, client/app/bundles/Events/components/EventActivityFeed.jsx, client/app/bundles/Events/components/PersonActivityFeed.jsx, client/app/bundles/Events/containers/AttendanceMatching.jsx, client/app/bundles/Events/containers/Dashboard.jsx, db/migrate/20170622195706_add_object_changes_to_versions.rb, db/schema.rb
=> 334 activity feed

client/app/bundles/Events/components/Tags.jsx, client/app/bundles/Events/containers/MemberDetail.jsx
Fixes edit and tag links on MemberDetail page
=> Member edit button

client/app/bundles/Events/components/Attendance.jsx, client/app/bundles/Events/components/Tags.jsx, client/app/bundles/Events/containers/MemberDetail.jsx, client/webpack.config.js, package.json
=> Facebook profile link

app/representers/json_api/member_representer.rb, client/app/bundles/Events/containers/MemberDetail.jsx
- added the member id to the member representer
- accessed that id in MemberDetail.jsx for the submit button
=> fixed edit button on membership profile

app/representers/json_api/member_representer.rb, client/app/bundles/Events/components/CustomFields.jsx, client/app/bundles/Events/containers/MemberDetail.jsx
=> Display custom fields for person record

app/controllers/events_controller.rb, client/app/bundles/Events/components/Events.jsx, client/app/bundles/Events/components/Members.jsx
Quick one here. should take care of https://github.com/advocacycommons/advocacycommons/issues/347
=> changes search text

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/members.js, app/controllers/members_controller.rb, app/models/api/action_network/import.rb, app/models/email_address.rb, app/models/person.rb, app/models/phone_number.rb, app/views/members/_email_address_fields.html.erb, app/views/members/_form.html.erb, app/views/members/_phone_number_fields.html.erb, app/views/members/edit.html.erb, app/views/members/new.html.erb, test/controllers/api/v1/people_controller_test.rb, test/controllers/imports_controller_test.rb, test/controllers/members_controller_test.rb, test/controllers/memberships_controller_test.rb, test/fixtures/people.yml, test/models/api/action_network/attendances_test.rb, test/models/api/action_network/people_test.rb, test/models/api/action_network/person_test.rb, test/models/group_test.rb, test/models/person_test.rb, test/representers/api/resources/person_representer_test.rb
- fixs failing test
- add cocoon gem to handle nested attributes in views.
Close #394.
=> [Issue #394] fixs create/edit members views and test

app/assets/stylesheets/application.scss, client/app/bundles/Events/components/SearchFilter.jsx
Solves issue https://github.com/advocacycommons/advocacycommons/issues/348
=> 348: Adds clear search button to undo filtering

app/assets/stylesheets/application.scss, app/controllers/members_controller.rb, app/models/person.rb, app/views/members/_person.json.jbuilder, app/views/members/show.json.jbuilder, client/app/bundles/Events/containers/MemberDetail.jsx
Add a toggle to set a Member to Organizer.
close #404
=> [issue #404]  Make a member an organizer

client/app/bundles/Events/components/SearchFilter.jsx
=> [Issue: 402] Only show clear button when there is some searchTerm

app/assets/stylesheets/application.scss, client/app/bundles/Events/components/TextEditor.jsx
=> Change the editor for the whiteboard

app/assets/stylesheets/active_admin.scss, app/views/active_admin/devise/passwords/edit.html.erb, app/views/active_admin/devise/passwords/new.html.erb, app/views/active_admin/devise/registrations/edit.html.erb, app/views/active_admin/devise/registrations/new.html.erb, app/views/active_admin/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, public/images/facebook-logo.svg
=> [issue 408] - Add facebook button design

client/app/bundles/Events/components/TextEditor.jsx
related to close issue [416](https://github.com/advocacycommons/advocacycommons/issues/416)
=> default should be wysiwyg for editing group description

client/app/bundles/Events/containers/MemberDetail.jsx
=> move organizer toggle button avobe Tags list

config/initializers/devise.rb
=> add facebook email scope

app/controllers/tags_controller.rb, test/controllers/tags_controller_test.rb
- Delete only tag for specific resource, not from tags table.
=> [Issue #422] Delete only tag for specific resource, not from tags table.

app/assets/stylesheets/application.scss, app/controllers/events_controller.rb, app/controllers/memberships_controller.rb, app/models/tag.rb, client/app/bundles/Events/components/Event.jsx, client/app/bundles/Events/components/Events.jsx, client/app/bundles/Events/components/Member.jsx, client/app/bundles/Events/components/Members.jsx, client/app/bundles/Events/components/MembersTable.jsx, client/app/bundles/Events/components/Tags.jsx, client/app/bundles/Events/containers/MemberDetail.jsx, client/app/bundles/Events/reducers/EventsReducer.jsx, client/app/bundles/Events/reducers/MembershipsReducer.jsx, test/fixtures/events.yml, test/models/tag_test.rb
- Add search existing tags to events ans members list
close 329.
=> [issue 329] Add search existing tags to events ans members list

app/controllers/application_controller.rb, app/controllers/groups_controller.rb, app/controllers/memberships_controller.rb, app/controllers/profile_controller.rb, app/controllers/tags_controller.rb, app/helpers/profile_helper.rb, app/models/ability.rb, app/models/group.rb, app/models/person.rb, client/app/bundles/Events/components/Breadcrumbs.jsx, client/app/bundles/Events/components/Events.jsx, client/app/bundles/Events/components/Member.jsx, client/app/bundles/Events/components/Members.jsx, client/app/bundles/Events/components/MembersTable.jsx, client/app/bundles/Events/components/Nav.jsx, client/app/bundles/Events/containers/Events.jsx, client/app/bundles/Events/containers/GroupDetail.jsx, client/app/bundles/Events/containers/Members.jsx, test/controllers/groups_controller_test.rb, test/controllers/members_controller_test.rb, test/models/ability_test.rb, test/models/group_test.rb
=> [Issue #389] public roster

app/assets/javascripts/mask.js, app/assets/javascripts/members.js, app/models/phone_number.rb, app/views/members/_phone_number_fields.html.erb, test/models/phone_number_test.rb
=> [issue 403] Fix phone number validation

app/controllers/events_controller.rb, client/app/bundles/Events/components/DateRange.jsx, client/app/bundles/Events/components/Events.jsx, client/app/bundles/Events/reducers/index.jsx, client/package.json, client/yarn.lock, db/schema.rb, test/controllers/events_controllers_test.rb
- Add Filter events by date
close #438.
=> [Issue #438] Add Filter events by date

client/app/bundles/Events/components/Member.jsx, client/app/bundles/Events/components/Members.jsx, client/app/bundles/Events/components/MembersTable.jsx, client/app/bundles/Events/containers/MemberDetail.jsx
=> Wrong group id in profile link

Gemfile, Gemfile.lock
- update nokogiri Gem to avoid security vulnerability.
=> update nokogiri Gem to avoid security vulnerability

app/controllers/application_controller.rb, app/controllers/events_controller.rb, app/controllers/memberships_controller.rb, client/app/bundles/Events/components/Events.jsx, client/app/bundles/Events/components/MembersTable.jsx
-  improve display of events.
Close #377.
=> [Issue #377] improve display of events

app/controllers/memberships_controller.rb, test/controllers/memberships_controller_test.rb
- fix sort by name in all members view
close #444.
=> [Issue #444] fix sort by name in all members view

app/controllers/memberships_controller.rb, client/app/bundles/Events/components/MembersTable.jsx, test/controllers/memberships_controller_test.rb
- Add sort by location to members list.
Closes #351.
=> [Issue #351] - Add sort by location to members list

client/app/bundles/Events/actions/EventsActions.jsx, client/app/bundles/Events/components/EventCreate.jsx, client/app/bundles/Events/components/Events.jsx, client/app/bundles/Events/reducers/EventReducer.jsx
Related to[ #439 ](https://github.com/advocacycommons/advocacycommons/issues/439)
=> Redirect to event show page after create a new event

client/app/bundles/Events/components/Events.jsx
=> Hide facebook import button from events page

client/app/bundles/Events/components/Events.jsx
=> remove duplicate class component for the member view

README.md
* needed as consequence of repo namechange specified in #463 
* side-effect: remove outdated "status" disclaimer
=> update readme to reflect new repo url

Gemfile, Gemfile.lock, Guardfile, app/assets/stylesheets/application.scss, app/assets/stylesheets/create_group_form.scss, app/assets/stylesheets/signup_form.scss, app/controllers/subgroups_controller.rb, app/models/event.rb, app/models/group.rb, app/models/membership.rb, app/views/subgroups/new.html.erb, config/routes.rb, test/controllers/members_controller_test.rb, test/controllers/memberships_controller_test.rb, test/controllers/subgroups_controller_test.rb, test/feature/subgroup_creation_test.rb, test/fixtures/groups.yml, test/models/group_test.rb
this resolves #502 and fulfills all acceptance criteria except for:
* logging in the organizer and redirecting them to dashboard, which is left to #506 
*  required fields which is left to #507 
Sorry. Too late and I'm too tired.
=> resolve "create standard rails form for subgroup and organizer creation"

app/controllers/dashboard_controller.rb, app/models/attendance.rb, app/models/event.rb, app/models/person.rb, client/app/bundles/Events/containers/Dashboard.jsx, test/fixtures/groups.yml, test/models/api/action_network/people_test.rb, test/models/group_test.rb
look, ma, no activity feed!
(used to look like this:)
=> resolve "kill the activity feed"

Procfile, config/puma.rb
(and leave comment where we diverge from automagically guessed web process)
=> [nostory] revise Procfile to match heroku defaults

app/services/google_api/create_google_group.rb
this (actually? hopefully?) resolves #570
=> [#570] more extensive error catching

app/models/group.rb, app/representers/json_api/group_representer.rb, app/services/subgroups/after_create.rb, client/app/bundles/Events/components/GroupResources.jsx, client/app/bundles/Events/containers/Dashboard.jsx, test/feature/subgroup_creation_test.rb, test/services/subgroups/after_create_test.rb
=> [#624] Added Google Group email to group dashboard.

client/app/bundles/Events/components/Nav.jsx, client/app/bundles/Events/containers/Members.jsx
=> [#621] Changed instances of text All Members to Members.

app/services/subgroups/after_create.rb, app/views/organizer_mailer/new_subgroup_email.text.erb, test/mailers/organizer_mailer_test.rb
(was showing link to old signup page)
=> [nostory|bugfix] update link in welcome email to new join page link

app.json, app/assets/stylesheets/buttons.scss
resolve #541 
--------
this tries to fix PR #647 by adding required env vars so we can test it on heroku, where the build is currently hanging...
=> resolve "login with google oauth"

config/environments/production.rb
* this resolves bug encountered QA'ing #541
* it also prevents exposing our users to identify theft :)
=> [nostory] force ssl for all requests

app.json, config/database.yml, lib/tasks/heroku.rake, test/feature/join_group_test.rb, test/test_helper.rb
resolves #641 
____________________________________________
* rebases @vaughanj10 's work onto master
* fixes FB stub in a less flaky way
* let's see if it works! :crossed_fingers:
=> resolve "#641 fix build pipeline"

app/controllers/concerns/signup_handlers.rb, app/controllers/concerns/signup_handlers/create_group.rb, app/controllers/concerns/signup_handlers/handler.rb, app/controllers/concerns/signup_handlers/join_group.rb, app/controllers/people/omniauth_callbacks_controller.rb
- clean up omniauth_controller to delegate all signup handling to
handler
- handler classes:
- classify member state (existing? needs info?, etc..) and...
- delegate to subclasses with handler methods appropriate to signup
path & member state
=> NOSTORY: add signup handler classes for create- & join-group paths

app/views/profile/_navigation.html.erb, client/app/bundles/Events/components/Header.jsx
=> Added My Groups link to header dropdown.

app/assets/stylesheets/join_group_page.scss, app/views/groups/join.html.erb
=> Added css for linebreaks in group description on join group page.

client/app/bundles/Events/components/GroupResources.jsx, client/app/bundles/Events/containers/Dashboard.jsx
=> Hide Edit Google Groups links from non organizers.

app/views/groups/_navigation.html.erb, client/app/bundles/Events/components/Nav.jsx, client/app/bundles/Events/containers/Events.jsx
=> Removed word all from all tabs.

client/app/bundles/Events/components/Breadcrumbs.jsx
=> Fixed broken breadcrumb link for group dashboard.

Gemfile, app/controllers/memberships_controller.rb, app/models/tag.rb, config/initializers/acts_as_taggable_on.rb, lib/tasks/qa.rake, test/controllers/tags_controller_test.rb, test/factories/group.rb, test/factories/membership.rb, test/factories/person.rb, test/factories/tag.rb, test/models/tag_test.rb
=> Fix tag queries memory bloat
