affinityworks/main

- .rubocop.yml
- app/models/api/events.rb
- app/models/event.rb
- test/fixtures/events.yml
- test/fixtures/files/events.json
- test/models/api/event_test.rb
- test/models/api/events_test.rb
Sensibly handle an AN import
* create new events
* merge attributes from more recent versions of existing events
* ignore existing, unchanged events
Also restructure the import code a bit.
I tested this with the API key and it worked! 🎉 
`DISABLE_SPRING=1 ACTION_NETWORK_API_TOKEN=${token} rails r 'Api::Events.import!'`
(The DISABLE_SPRING is needed if ACTION_NETWORK_API_TOKEN wasn't set before Rails Spring started)
> #13 OSDI Action Network import merge

- app/models/concerns/api/identifiers.rb
- app/models/email_address.rb
- test/models/email_address_test.rb
> Use person hashed primary email as affinity identifier.

- app/controllers/application_controller.rb
- app/models/ability.rb
- app/models/membership.rb
- test/models/ability_test.rb
- test/models/membership_test.rb
related to #104. Please let me know if I misunderstood the roles. Because right now we have `member` and `organizer` inside the Membership and `admin` inside the Person.
> Redirect non organizer group members to group public page after logs in.

- app/assets/stylesheets/application.scss
- app/controllers/application_controller.rb
- app/models/group.rb
- app/representers/json_api/member_representer.rb
- app/representers/json_api/membership_group_representer.rb
- app/representers/json_api/membership_representer.rb
- client/app/bundles/Events/actions/MembershipsActions.jsx
- client/app/bundles/Events/components/Member.jsx
- client/app/bundles/Events/components/Members.jsx
- client/app/bundles/Events/containers/Members.jsx
- client/app/bundles/Events/utils/Pathnames.jsx
- config/routes.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/attendances_controller_test.rb
- test/controllers/memberships_controller_test.rb
related to #262. 
1) The group link is pointing to the public group page because of a member may also be a member of a group for which the nat organizer has no permissions. We can change this behavior.
2) Right now we are always showing the 'Group name' column because we need the  groups relations to know if we should show or hide that column.
> 262 group name on all members

- app/assets/stylesheets/active_admin.scss
Fixes #379 
It looked like we were surfacing errors in multiple places on the login page. So I am suppressing a particular error that was being shown multiple times. The h2 selector was being overwritten by line 26 of active_admin.scss
Would encourage use of class level CSS over element targeting to prevent funky issues like this in the future.
Before:
After:
> Fixes double logo on password reset

- client/app/bundles/Events/components/Events.jsx
> [Issue #349] Hide facebook import button from events page

- README.md
- bin/env
- config/database.yml
- package.json
Resolves #465 and fulfills its acceptance criteria.
* list all dependencies and version numbers
* translate all instructions into bash commands
* provide variations for Mac and Debian where applicable
* side-effect: add password for local dev db
(necessary to run on aguestuser's postgres config)
> [#465] clarify dev env steps in readme

- app/models/person.rb
* BUG: loading dashboard after destorying a Person flashes an error
* CAUSE: `version.item.name` throws b/c `item` is nil (not sure why!)
* FIX: use lonely operator to guard against nil values
This does not address the underlying problem, but provides a safe
patch for now.
> [bugfix] provide nilcheck in activity feed json serialization

- app/assets/stylesheets/create_group_form.scss
- app/controllers/subgroups_controller.rb
- app/models/concerns/can_signup.rb
- app/models/group.rb
- app/models/person.rb
- app/views/active_admin/devise/registrations/edit.html.erb
- app/views/subgroups/new.html.erb
- test/feature/subgroup_creation_test.rb
- test/fixtures/people.yml
- test/models/concerns/can_signup_test.rb
- test/models/group_test.rb
this resolves #512 and fulfills its acceptance criteria
-------------
* condense validation checks by using nested attrs
* redirect to profile page (not dashboard)
* fix failing test for `Person.create_from_signup` (new memberhsip was
not being crewated b/c fixture had invalid phone number -- FUN!!!)
* refactor `Person.create_from_signup` to use nested attrs
* fix bug causing nested field values to disappear on error
re-render (caused by not derriving all `field_for` second arguments
from the top level @subgroup instance variable -- YES it's weird we
have to do this. i didn't make the rails rules, i just play by them)
* add red border styling to error messages
> resolve "login creator of subgroup after subgroup creation"

- app/assets/stylesheets/create_group_form.scss
- app/controllers/subgroups_controller.rb
- app/models/concerns/can_signup.rb
- app/models/group.rb
- app/models/person.rb
- app/views/active_admin/devise/registrations/edit.html.erb
- app/views/subgroups/new.html.erb
- test/feature/subgroup_creation_test.rb
- test/fixtures/people.yml
- test/models/concerns/can_signup_test.rb
- test/models/group_test.rb
this resolves #514 and fulfils its AC's
Look, ma, no summary field!
please merge #517 before reviewing this. (that will drop commit 
6099b79  from the PR, as intended)
> resolve  "remove summary field from subgroup creation form"

- app/assets/stylesheets/create_group_form.scss
- app/models/phone_number.rb
- test/models/phone_number_test.rb
this resolves #511 and fulfills its ACs.
------------------------------------------------------
Here are some sample numbers:
(734) 555 1212
(734) 555.1212
(734) 555-1212
(734) 5551212
(734)5551212
734 555 1212
734.555.1212
734-555-1212
7345551212
+1-123-456-7890
+1 123-456-7890
+43-123-456-7890
+43 123-456-7890
123456-7890
345551212
(34) 555 1212
734-555-1212 ext 2
7345551212!
+433 123-456-7890
1212sdfsd2121
(12)
this is a #%(%& garbage string 31
this is a garbage string 318
1212/1212
make group creation form description textarea larger so it lines up with group fields (was supposed to happen in last PR)
> resolve "relax phone number validation

- app/models/concerns/networkable.rb
- app/models/group.rb
- app/models/network.rb
- app/models/network_membership.rb
- app/services/README.md
- app/services/feature_toggle.rb
- client/app/bundles/Events/components/Nav.jsx
- client/app/bundles/Events/containers/Dashboard.jsx
- config/application.rb
- config/feature_toggles.yml
- config/networks.yml
- db/migrate/20180320172047_create_network.rb
- db/migrate/20180320182830_create_network_memberships.rb
- db/migrate/20180321021928_add_indexes_to_network_memberships.rb
- db/schema.rb
- test/fixtures/addresses.yml
- test/fixtures/groups.yml
- test/fixtures/network_memberships.yml
- test/fixtures/networks.yml
- test/models/concerns/networkable_test.rb
- test/models/group_test.rb
- test/models/network_membership_test.rb
- test/models/network_test.rb
- test/services/feature_toggle_test.rb
This partially completes #523 
* add `Network` model, which  must have a unique name
* groups can:
* be member of a network (via a `NetworkMembership`)
* have a primary network
* not have more than one primary network
* not become member of same network twice
* enumerate the names of networks for which a given feature is to be disabled or enabled (relying on the strong guarantee that networks must have unique, immutable names)
* when calling `FeatureToggle.on?(:some_feather, some_group)`, inspect whether `some_group.primary_network.name` is included in the enumerated list of black- or white-listed network names to determine whether the toggle should be on or off
* note: `some_group` can always be ascertained by calling `current_group`
* when called (eg from the public subgroup creation …
> partially resolve "feature toggle for events tab"

- Procfile.dev
* BUG: app fails in production after PRs that introduce migrations
* CAUSE: heroku does not run migrations without `release` task
specifying to do so
* FIX: add a `release` task to run migrations
> [nostory] fix heroku migration bug

- Procfile
- config/puma.rb
* it references puma config file, so clean that up
* motivation: we don't have a prod Procfile, so heroku guesses
* but we *need* a prod Procfile for heroku to run our migrations properly
> [nostory] provide prod Procfile

- app/views/subgroups/new.html.erb
- test/feature/subgroup_creation_test.rb
* resolves #507 and #542 
* require group name, organizer email/password/first name/last name
* list email & password first for consistency
> resolve "add required fields to subgroup creation page"

- client/app/bundles/Events/components/Member.jsx
- client/app/bundles/Events/components/MembersTable.jsx
This resolves #548 and fulfills its acceptance criteria.
* BUG: in member lists for groups that are leaves in affiliation trees (but not for root-node groups -- ie: parent groups), the column contents are shifted one column to the right from the headers (starting at the "tags" column)
* CAUSE: at such levels, business logic dictates that we hide the  group name, which we were seeking to accomplish by rendering empty `<th>` and `<td>` tags for columns and cells (respectively). styling was causing the `<td>` tags to collapse, but not the `<th>` tags.
* FIX: instead of reasoning about widths, if we are supposed to hide the group column, just don't render `<th>` or `<td>` tags at all. problem solved.
**before**
**after**
> resolve  "align columns with headers on members list page"

- client/app/bundles/Events/components/Group.jsx
this resolves #513 and fulfills its AC's by doing the following:
* supress undefined city/state/zip values when any are not present
* show all city/state/zip values when any are present
* BUG: when a group has a zipcode but no city or state, the groups
table displays "undefined" for the latter two values
* CAUSE: lack of proper null-filtering
* FIX: provide proper null-filtering
**before:**
**after:**
> [#548] fix undefined location values bug

- client/app/bundles/Events/components/Attendance.jsx
- client/app/bundles/Events/components/EmailLink.jsx
- client/app/bundles/Events/components/Member.jsx
- client/app/bundles/Events/components/MembersTable.jsx
- client/app/bundles/Events/containers/EventDetail.jsx
- client/app/bundles/Events/containers/MemberDetail.jsx
This resolves #552 
* if i have gmail set as my default mail client (:sob: ), then clicking mailto links will open in a new tab, not replace the app
**clicking:**
**new tab:**
> [#552] clicking all mailto links now opens new tab

- app/models/group.rb
* BUG: active record throws error when deleting a group that has a custom form
* CAUSE: we violate a foreign key constraint that by not deleting the custom form when we delete the group
* FIX: add a `dependent: :destroy` helper to delete associated custom forms when we delete a group
> [bug] fix destroy dependency btw/ group & custom from

- app/models/custom_form.rb
- app/models/group.rb
- app/models/signup_form.rb
- app/representers/json_api/group_representer.rb
- client/app/bundles/Events/components/GroupResources.jsx
- client/app/bundles/Events/containers/Dashboard.jsx
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- test/controllers/api/v1/people_controller_test.rb
- test/fixtures/custom_forms.yml
- test/fixtures/forms.yml
- test/models/custom_form_test.rb
- test/models/group_test.rb
- test/models/signup_form_test.rb
resolves #554 
* create a new "Resources" section on the Group dashboard
* link to the signup page in it
* store the signup url according to OSDI schema (ie: as a `browser_url` on a `form` entity)
* encapsulate retrieval of url with `Group#signup_url`
* add `signup_url` to `Group` Roar representer
* add `GroupResources` component, use it to display link
hovering over signup pae link (see url bottom-left):
slicking on singup page link:
> resolve "link to signup page from group dashboard"

- app/models/group.rb
- lib/tasks/heroku.rake
- test/models/group_test.rb
this provides a cleanup to #600 and thus actually resolves #554 
this is a pretty weedy fix intended to prevent confusing discrepancies between review apps and dev or staging and prod from arising during the review process.
if you care to read the gory details... we use derrived values for the signup_url display link in group dashboard (instead of the value persisted in `group.signup_forms.first.browser_url`):
* turns out this is less complicated b/c staging apps & dev share a db, so if we use the persisted url as the display value, then dev will always show (dead) links that include the hostname for (deleted) review apps as the base of the url
* to eliminate confusion in the review process, just use a derrived value, which will always know the correct hostname and thus never
produce …
> cleanup 'resolve "link to signup page from group dashboard"'

- client/app/bundles/Events/components/TextEditor.jsx
Fixes bugs found by @Matt-Holland in #596 
and thus resolves #568
> [#568] Use "Whiteboard" in text-editor edit mode

- app/models/address_input_group.rb
- app/models/custom_form.rb
- app/models/form_input_group.rb
- app/models/signup_form.rb
- app/services/migration.rb
- app/views/signups/new.html.erb
- lib/tasks/heroku.rake
- test/feature/signup_test.rb
- test/models/concerns/can_signup_test.rb
- test/models/custom_form_test.rb
- test/models/form_input_group_test.rb
- test/models/signup_form_test.rb
- test/services/migration_test.rb
this resolves #521
___________________________
* add optional phone number field to signup form
* require all other fields
PLEASE NOTE: I saw and ignored many things we could improve in the signup form (for example adding password field, logging user in after signup, etc...) because they are part of a bigger UX overhaul discussed in #573 and have (i think) been explicitly descoped from the "must have for soft launch" bucket of work
Revised fields (w/ required labels):
Submitting without filling in required fields:
> resolve "revise signup form fields"

- config/initializers/devise.rb
this resolves #598 
* disable the FB OAuth events scope since it requires a review process we have not completed (and is also broken)
* as a result, prevent users from seeing scary warning when they login w/ FB
before disabling (scary!):
after disabling (not scary!)
> resolve "disable fb events permissions"

- app/models/concerns/url_helpers.rb
- app/models/group.rb
- app/representers/json_api/group_representer.rb
- client/app/bundles/Events/components/GroupResources.jsx
- client/app/bundles/Events/containers/Dashboard.jsx
- test/models/group_test.rb
resolves #599 
_____________________________________
* include a link to new subgroup form in resources list (since we're always trying to remember that, organizers likely will too!)
* reword resources listings to "recruit new _____" (member or subgroup)
* add `UrlHelpers` concern (to type less when using url helpers in model code)
> resolve "link to subgroup creation form in dashboard resources"

- app/assets/stylesheets/application.scss
- app/views/layouts/_modal_header.html.erb
- app/views/members/_form.html.erb
- app/views/members/edit.html.erb
- app/views/members/new.html.erb
resolves #593 
_____________________________
* instead of fixing tab mess, hide it!
* whenever we add or edit a member, hide all the chorme
* provide a "cancel" button to take user back to either members list (if adding) or member profile (if editing)
* bonus: reword test on edit member page that used to say "Edit Person"
new member page:
edit member page:
> resolve "add/edit member in a 'modal'"

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/member_form.scss
- app/controllers/members_controller.rb
- app/models/signup_form.rb
- app/services/migration.rb
- app/views/members/_email_address_fields.html.erb
- app/views/members/_form.html.erb
- app/views/members/_phone_number_fields.html.erb
- app/views/members/edit.html.erb
- app/views/subgroups/new.html.erb
- test/feature/add_edit_member_test.rb
- test/models/signup_form_test.rb
resolves #607 
________________________________
* removes gender, gender identity, party, birthday fields
* adds zipcode field (and ensures it belongs to *primary* address)
* restyles add/edit member forms to with more compact layout
> resolve "revise fields in add/edit member form"

- app/services/google_api/service.rb
- test/services/google_api/service_test.rb
* bug: some groups exist in networks that have gsuite support enabled, but we  did not store google group id's for them when they were created. thus, when we try to fetch their google group from the google API, we pass a nil `group_key` and we get a (maddeningly opaque!) `Bad Reqeust` error
* fix: check to see if `group_key` is nil, and don't hit the google api if it is
> [bugfix] don't fetch google groups when group has no `group_key`

- app/controllers/signups_controller.rb
- test/feature/signup_test.rb
this resolves #617 
* title says it all: login and redirect a newly signed up member after they fill out signup form (via "email path")
* note that we do *not* require a password for this login
* yes, that's weird. we'll fix it in #613
before clicking submit:
after clicking submit:
after clicking on group name (note as a member -- not an organizer -- you don't see the full page):
> resolve "login user after email signup"

- app/mailers/organizer_mailer.rb
- test/feature/subgroup_creation_test.rb
- test/mailers/organizer_mailer_test.rb
- test/services/subgroups/after_create_test.rb
fixes new bug introduced by #635 
* remove signup form argument (so mailer won't fail)
* fix broken tests that still provide that argument
> [nostory|bug] cleanup fix to signup link in welcome email

- app/controllers/members_controller.rb
- app/controllers/people/omniauth_callbacks_controller.rb
- app/models/identity.rb
- app/models/person.rb
- test/feature/join_group_test.rb
resolves #611 
resolves #612 
fixes bug found in @Matt-Holland 's review of #652 
__________________________________________________________________
* if a user already has an account on affinity with an email address matching their FB or Google identity, when they join a group via OAuth:
*  do not try to create a new person
* rather: find the existing person and update the appropriate membership, contact info, and identity associations to reflect their OAuth data and new group
* do *not* update their name to match what we found in OAuth, assume the name they gave us in Affinity is what they want
* if a user does not have an account, proceed as before
> support 2-step oauth group join for existing users (resolves #611, #612, fixes #652)

- app/assets/stylesheets/buttons.scss
- app/assets/stylesheets/join_group_page.scss
- app/controllers/application_controller.rb
- app/controllers/groups_controller.rb
- app/controllers/memberships_controller.rb
- app/models/person.rb
- app/views/groups/_already_joined_notice.html.erb
- app/views/groups/_join_buttons_logged_in.html.erb
- app/views/groups/_join_buttons_logged_out.html.erb
- app/views/groups/join.html.erb
- config/routes.rb
- test/feature/join_group_test.rb
- test/routes/membership_routes_test.rb
resolves #653 
* if a logged-in user doesn't belong to a group:
* show a "join" button on the join page
* when they click it, they are added to the group, forwarded to its dashboard
* if a logged-in user *does* belong to a group:
* show an "already joined" notice
* link to the dashboard page
> resolves "#653 join group as logged in user"

- app/assets/stylesheets/create_group_form.scss
- app/controllers/members_controller.rb
- app/controllers/subgroups_controller.rb
- app/models/concerns/can_signup.rb
- app/views/layouts/application.html.erb
- app/views/layouts/signup.html.erb
- app/views/members/_signup_form_oauth.html.erb
- app/views/members/signup_form_email.html.erb
- app/views/shared/_modal_actions.html.erb
- app/views/shared/_signup_error_alert.html.erb
- app/views/shared/_signup_fields_email.html.erb
- app/views/subgroups/_organizer_info_logged_out.html.erb
- app/views/subgroups/_submit_logged_in.html.erb
- app/views/subgroups/_submit_logged_out.html.erb
- app/views/subgroups/new.html.erb
- app/views/subgroups/signup_form_email.html.erb
- client/app/bundles/Events/containers/AttendanceForm.jsx
- config/routes.rb
- lib/tasks/heroku.rake
- test/feature/create_group_test.rb
- test/models/concerns/can_signup_test.rb
- test/routes/signup_routes_test.rb
resolves #665 
_________________________
* on step 1, gather info about group
* offer choice of submit buttons (currently only "create with email" exists)
* validate group field submissions, if valid..
* proceed to step 2, where we...
* gather info about organizer, if valid...
* create group, organizer, membership, google group
* sign in and redirect organizer to group dashboard page
side-effects:
* extract `signup` layout, share it between signup flows (join- & create-group)
* extract `signup_fields_email` partial, share between signup flows
* re-introduce (and re-write) `Person.build_for_signup`
* standardize formatting of "Zip Code", "Create with Email"`
*Step 1:*
*Step 2:*
*End Result:*
> resolve "[#665] add flow to create group w/ email signup for logged-out users"

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/members_controller.rb
- app/models/ability.rb
- app/models/group.rb
- test/controllers/members_controller_test.rb
- test/models/ability_test.rb
- test/models/group_test.rb
Closes #663 
_______________________
* **BUG:** if I am a member of a group (not an organizer) clicking "account" in the nav dropdown redirects to /home instead my account edit page
* **CAUSE:** group-based permissions only allow organizers to edit a group member
* **FIX:** introduced person-based permissions and allow a person to edit themselves
> Fix Account Redirect

- app/models/concerns/bulk_import.rb
- app/models/group.rb
- app/services/members/after_create.rb
- test/models/concerns/bulk_import_test.rb
resolves #677 
___________________________________
* allows an admin to bulk import a CSV list of members into a group from the rails console as follows:
```ruby
> group = Group.find(1)
> csv = <paste csv string here>
> group.bulk_import_members(csv)> 
```
* create `BulkImport` concern and include it on `Group`
* it exposes `.bulk_import_members`, which:
* takes a csv string
* imports all valid rows as new group members
* raises an error for malformed rows (after importing well-formed ones)
* raises an error if headers are malformed (and imports nothing)
```ruby
> group = Group.first
> group.network_memberships # make sure its a member of NationalNetwork
> csv = "first_name,last_name,email,zip_code,phone\n" +
"alice,foo,alice@anarchist.website,11111,222-222-2222\n" + …
```
> resolve #677 -- "import members to group from CSV" 

- Procfile.dev
- app/mailers/group_mailer.rb
- app/services/members/after_create.rb
- app/services/subgroups/after_create.rb
- app/views/group_mailer/create_group_email.text.erb
- app/views/group_mailer/join_group_email.text.erb
- bin/run
- test/feature/join_group_test.rb
- test/mailers/group_mailer_test.rb
- test/models/concerns/bulk_import_test.rb
- test/services/members/after_create_test.rb
- test/services/subgroups/after_create_test.rb
resolve #579 
________________________
* create `join_group_email` that provides all links specified in Acceptance Criteria for #677 
* send this email in `Members::AfterCreate`
* refactor `Subgroups::AfterCreate` to also send this email (ie: send same email whether you created a group or joined one)
side-effects:
* add unit tests for `Members::AfterCreate`
* light touch-up to `Subgroups::AfterCreate` unit tests
* rename mailer classes, methods
* streamline dev env invocations of resque
* if a user already exists with email you want to use, destroy it
* go to `/groups/2/join`
* fill out form using an email you control 
* check to see if you got a welcome email
* destroy the person you just created in last test
* follow the happy path QA instructions in #680 
* check to see if you got a …
> resolve #579 - "welcome email for new group members"

- app/assets/stylesheets/active_admin.scss
- app/assets/stylesheets/buttons.scss
- app/assets/stylesheets/member_form.scss
- app/helpers/devise_helper.rb
- app/views/active_admin/devise/passwords/new.html.erb
- app/views/active_admin/devise/sessions/new.html.erb
- config/locales/devise.en.yml
resolves #679 
______________________________
* in all cases that a user tries to login with email not in system:
* display error message styled like other error messages on site
* suggest that user might be using email different than signup email
* suggest contacting support if problems persist
* for oauth: display error message immediately on login page
* for email: display error on password reset page after trying to
lookup email for password reset flow
* add styling for oauth errors
* add `app/helpers/devise_helper.rb` to override standard behavior as
suggested here: https://github.com/plataformatec/devise/wiki/Override-devise_error_messages!-for-views
**error message in email flow:**
**error message in facebook flow:**
**error message in google flow:**
1. Login to both Facebook and …
> resolve #679 - "handle login with wrong email addresses"
